steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/sb-hello-world-234105/$REPO_NAME:$COMMIT_SHA', '.']
images: ['gcr.io/sb-hello-world-234105/$REPO_NAME:$COMMIT_SHA']

